environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

platform: Any CPU
configuration: Release

before_build:
  - dotnet restore SonicArranger.sln --verbosity normal

build:
  parallel: true
  project: SonicArranger.sln

artifacts:
  - path: SonicConvert-Windows.zip
    name: SonicConvert-Windows
  - path: SonicConvert-Windows32Bit.zip
    name: SonicConvert-Windows32Bit
  - path: SonicConvert-Linux.tar.gz
    name: SonicConvert-Linux
  - path: SonicConvert-Windows-Standalone.zip
    name: SonicConvert-Windows-Standalone
  - path: SonicConvert-Windows32Bit-Standalone.zip
    name: SonicConvert-Windows32Bit-Standalone
  - path: SonicConvert-Linux-Standalone.tar.gz
    name: SonicConvert-Linux-Standalone
  - path: nuget\*.nupkg
    name: NugetPackages

after_build:
    - ps: if ($env:APPVEYOR_REPO_TAG -eq $true) { ./publish.ps1 }
    - ps: ./nuget.ps1

test: off

deploy:
  - provider: GitHub
    name: SonicConvert-Windows
    artifact: SonicConvert-Windows
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: SonicConvert-Windows32Bit
    artifact: SonicConvert-Windows32Bit
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: SonicConvert-Linux
    artifact: SonicConvert-Linux
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: SonicConvert-Windows-Standalone
    artifact: SonicConvert-Windows-Standalone
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: SonicConvert-Windows32Bit-Standalone
    artifact: SonicConvert-Windows32Bit-Standalone
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
  - provider: GitHub
    name: SonicConvert-Linux-Standalone
    artifact: SonicConvert-Linux-Standalone
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release $(APPVEYOR_REPO_TAG_NAME)'
    auth_token:
      secure: ku89dMTVkz+PE5bvxWQCLG9PbNTa9tQUsidZ/7726rLEZjIAvDcxEC668Ix9zYmw
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: false
  - provider: NuGet
    name: NugetPackages
    api_key:
      secure: kv2Z0jPlIGPPryGlyqN+SgqEOXcI7KF3/shfkRVgPTq7D2/QFi4vw+TKb/CTaWTY
    skip_symbols: true
